/**
 * One-time script: upload all public assets to Cloudinary
 * Run from project root:  node scripts/upload-assets.js
 */
require('dotenv').config({ path: './server/.env' });
const cloudinary = require('cloudinary').v2;
const fs = require('fs');
const path = require('path');

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key:    process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const ASSETS_DIR = path.join(__dirname, '../client/public');
const OUT_FILE   = path.join(__dirname, '../client/src/assets/cloudinaryAssets.js');

// Files to upload and what public_id to give them
const FILES = [
  { file: 'DOLOGONLOGO.jpg',    id: 'irequestdologon/assets/DOLOGONLOGO',    type: 'image' },
  { file: 'MARAMAGLOGO.jpg',    id: 'irequestdologon/assets/MARAMAGLOGO',    type: 'image' },
  { file: 'BARANGAYHALL.jpg',   id: 'irequestdologon/assets/BARANGAYHALL',   type: 'image' },
  { file: 'bg-musuan.jpg',      id: 'irequestdologon/assets/bg-musuan',      type: 'image' },
  { file: 'GCASH.jpg',          id: 'irequestdologon/assets/GCASH',          type: 'image' },
  { file: 'GCASH.png',          id: 'irequestdologon/assets/GCASH-png',      type: 'image' },
  { file: 'myofficialgcash.jpg',id: 'irequestdologon/assets/myofficialgcash',type: 'image' },
  { file: 'PAYMONGO.jpg',       id: 'irequestdologon/assets/PAYMONGO',       type: 'image' },
  { file: '1PESO.jpg',          id: 'irequestdologon/assets/1PESO',          type: 'image' },
  { file: 'bikerider.png',      id: 'irequestdologon/assets/bikerider',      type: 'image' },
  { file: 'dologonhallicon.png',id: 'irequestdologon/assets/dologonhallicon',type: 'image' },
  { file: 'secretarydesk.png',  id: 'irequestdologon/assets/secretarydesk', type: 'image' },
  { file: 'DOLOGONBGVIDEO.mp4', id: 'irequestdologon/assets/DOLOGONBGVIDEO', type: 'video' },
];

async function uploadAll() {
  const results = {};
  let passed = 0;
  let failed = 0;

  console.log(`\nUploading ${FILES.length} assets to Cloudinary…\n`);

  for (const { file, id, type } of FILES) {
    const filePath = path.join(ASSETS_DIR, file);
    if (!fs.existsSync(filePath)) {
      console.warn(`  ⚠  SKIP  ${file}  (not found)`);
      failed++;
      continue;
    }

    try {
      const result = await cloudinary.uploader.upload(filePath, {
        public_id: id,
        resource_type: type,
        overwrite: true,
      });
      const key = path.basename(file, path.extname(file)).replace(/[^a-zA-Z0-9]/g, '_');
      results[key] = result.secure_url;
      console.log(`  ✔  ${file.padEnd(26)} → ${result.secure_url}`);
      passed++;
    } catch (err) {
      console.error(`  ✖  ${file.padEnd(26)}   ERROR: ${err.message}`);
      failed++;
    }
  }

  // Write assets file for React
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  const content = `// Auto-generated by scripts/upload-assets.js — do not edit manually
const assets = ${JSON.stringify(results, null, 2)};

export default assets;
`;
  fs.writeFileSync(OUT_FILE, content, 'utf8');

  console.log(`\n─────────────────────────────────────────`);
  console.log(`  Done: ${passed} uploaded, ${failed} failed`);
  console.log(`  Assets file written to:\n  ${OUT_FILE}`);
  console.log(`─────────────────────────────────────────\n`);
}

uploadAll();
