const fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const qaTemp=path.join(process.env.TEMP,'irequest-qa-20261003');
(async()=>{
  const {marked}=await import(pathToFileURL(path.join(qaTemp,'node_modules/marked/lib/marked.esm.js')).href);
  const {chromium}=require(path.join(qaTemp,'node_modules/playwright'));
  const markdown=fs.readFileSync(path.join(__dirname,'QA-REPORT.md'),'utf8');
  const body=marked.parse(markdown).replace(/<p><strong>(QA-\d+)/g,'<p class="finding"><strong>$1');
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>iRequestDologon QA Report — 3 October 2026</title><style>
  *{box-sizing:border-box}body{margin:0;background:#edf2ef;color:#182b23;font:15px/1.6 system-ui,-apple-system,Segoe UI,sans-serif}main{max-width:1100px;margin:30px auto;padding:52px 60px;background:#fff;border-top:8px solid #135d3c;box-shadow:0 8px 35px #16322412}h1{font-size:32px;line-height:1.2;letter-spacing:-.7px;margin-top:0}p{margin:14px 0}a{color:#126342;text-decoration:underline;overflow-wrap:anywhere}code{font:12px/1.5 Consolas,monospace;background:#eef4f0;padding:1px 4px;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;margin:20px 0 26px;font-size:13px}th,td{border:1px solid #dbe3dd;text-align:left;padding:10px 12px;vertical-align:top}th{background:#edf5ef;color:#13472d}tr:nth-child(even){background:#fafcfb}.finding{font-size:18px;color:#135d3c;border-top:1px solid #dbe3dd;padding-top:22px;margin-top:30px;break-after:avoid}strong{font-weight:650}li{margin:8px 0}pre{white-space:pre-wrap;padding:15px;background:#eef4f0}.evidence{break-before:page}.evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.evidence-grid figure{margin:0;break-inside:avoid}.evidence-grid img{width:100%;max-height:600px;object-fit:contain;object-position:top;border:1px solid #dbe3dd}.evidence-grid figcaption{font-size:12px;margin-top:8px;color:#496052}.print{position:fixed;right:20px;bottom:20px;background:#135d3c;color:white;border:0;padding:12px 18px;border-radius:8px;cursor:pointer}@media(max-width:700px){main{margin:0;padding:25px 18px}table{font-size:11px}th,td{padding:6px}.evidence-grid{grid-template-columns:1fr}}@media print{body{background:white;font-size:9.6pt;line-height:1.43}main{margin:0;padding:0;max-width:none;border:0;box-shadow:none}h1{font-size:25pt}table{font-size:8pt;margin:12px 0 17px}th,td{padding:6px}thead{display:table-header-group}tr{break-inside:avoid}.finding{font-size:12.5pt;margin-top:19px;padding-top:13px}p{orphans:3;widows:3}.print{display:none}.evidence-grid img{max-height:205mm}.evidence-grid figcaption{font-size:8pt}a{color:#135d3c}}
  </style></head><body><main>${body}<div class="evidence"><p class="finding"><strong>Selected visual evidence</strong></p><p>All shown residents and requests are synthetic QA fixtures.</p><div class="evidence-grid"><figure><img src="screenshots/resident-dashboard-outage.png" alt="Resident dashboard during a simulated API outage"><figcaption>QA-16: HTTP 503 is presented as an empty request list, with no visible retry action.</figcaption></figure><figure><img src="screenshots/kiosk-review-pricing-outage.png" alt="Kiosk review page during a pricing outage"><figcaption>QA-17: Submit remains available when the review page has no price.</figcaption></figure></div></div></main><button class="print" onclick="window.print()">Print / Save PDF</button></body></html>`;
  const htmlFile=path.join(__dirname,'QA-REPORT.html');fs.writeFileSync(htmlFile,html);
  const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  try{const page=await browser.newPage();await page.goto(pathToFileURL(htmlFile).href,{waitUntil:'load'});await page.pdf({path:path.join(__dirname,'QA-REPORT.pdf'),format:'A4',printBackground:true,margin:{top:'17mm',bottom:'18mm',left:'15mm',right:'15mm'},displayHeaderFooter:true,headerTemplate:'<span></span>',footerTemplate:'<div style="font-size:8px;width:100%;text-align:center;color:#6b7770">iRequestDologon · QA review · 3 October 2026 &nbsp; | &nbsp; <span class="pageNumber"></span> / <span class="totalPages"></span></div>'});await page.screenshot({path:path.join(__dirname,'screenshots/report-preview.png'),fullPage:false});console.log(JSON.stringify({html:htmlFile,pdf:path.join(__dirname,'QA-REPORT.pdf'),pdfBytes:fs.statSync(path.join(__dirname,'QA-REPORT.pdf')).size}));}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
