// Shared, presentable exports for every report in the portal.
//
// Both the PDF and the Excel (.xlsx) exports share one letterhead: the Barangay
// Dologon seal, the system name, the report title, when it was generated and by
// whom. Call exportReportPDF / exportReportXLSX with the same { columns, rows }
// shape a screen already has, so each screen stays a thin caller.

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';

const GREEN = [21, 109, 7]; // #156D07 — the portal's brand green
const ORG = 'Barangay Dologon, Maramag, Bukidnon';
const SYSTEM = 'iRequestDologon System';

// The seal lives in /public so it loads same-origin (no CORS taint) and is
// cached after the first export.
let sealPromise = null;
function loadSeal() {
  if (!sealPromise) {
    sealPromise = fetch('/report-seal.png')
      .then((r) => (r.ok ? r.blob() : Promise.reject()))
      .then(
        (blob) =>
          new Promise((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(String(reader.result));
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
          })
      )
      .catch(() => null); // Missing seal must never break an export.
  }
  return sealPromise;
}

function stamp(user) {
  const when = new Date().toLocaleString('en-PH', {
    year: 'numeric', month: 'short', day: '2-digit',
    hour: '2-digit', minute: '2-digit', hour12: true,
  });
  const who = user?.fullName
    ? `${user.fullName}${user.role ? ` (${user.role})` : ''}`
    : 'Unknown';
  return { when, who };
}

// Filenames carry the date so downloads don't collide.
function stampedName(base, ext) {
  const d = new Date().toISOString().slice(0, 10);
  return `${base}-${d}.${ext}`;
}

/**
 * Presentable PDF with the shared letterhead.
 * @param {object}   o
 * @param {string}   o.title       report title, e.g. "Purok Clearance Fee Report"
 * @param {string}   [o.subtitle]  e.g. "Purok 20 · All records"
 * @param {string[]} o.columns     table headers
 * @param {Array[]}  o.rows        table body rows (arrays aligned to columns)
 * @param {Array}    [o.foot]      optional footer row (totals)
 * @param {object}   o.user        current admin { fullName, role }
 * @param {string}   o.filename    base filename, no extension
 * @param {'portrait'|'landscape'} [o.orientation]
 * @param {object}   [o.columnStyles] autoTable columnStyles passthrough
 */
export async function exportReportPDF({
  title, subtitle, columns, rows, foot, user, filename,
  orientation = 'portrait', columnStyles,
}) {
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const { when, who } = stamp(user);

  const seal = await loadSeal();
  if (seal) {
    try { doc.addImage(seal, 'PNG', 14, 10, 18, 18); } catch { /* ignore bad image */ }
  }
  const textX = seal ? 36 : 14;

  doc.setTextColor(...GREEN);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(ORG, textX, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(130, 130, 130);
  doc.text(SYSTEM, textX, 20);

  doc.setTextColor(30, 30, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(title, textX, 26);
  let y = 26;
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(110, 110, 110);
    doc.text(subtitle, textX, 31);
    y = 31;
  }

  // Divider + generation stamp.
  y += 5;
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.4);
  doc.line(14, y, pageW - 14, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated: ${when}`, 14, y);
  doc.text(`Generated by: ${who}`, pageW - 14, y, { align: 'right' });

  autoTable(doc, {
    startY: y + 4,
    head: [columns],
    body: rows,
    ...(foot ? { foot: [foot] } : {}),
    styles: { fontSize: 9, cellPadding: 2.5, overflow: 'linebreak' },
    headStyles: { fillColor: GREEN, textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [240, 253, 244], textColor: GREEN, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    ...(columnStyles ? { columnStyles } : {}),
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      // Page footer with number.
      const page = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(160, 160, 160);
      doc.text(
        `${SYSTEM}  ·  Page ${data.pageNumber} of ${page}`,
        pageW / 2, doc.internal.pageSize.getHeight() - 8, { align: 'center' }
      );
    },
  });

  doc.save(stampedName(filename, 'pdf'));
}

/**
 * Presentable Excel (.xlsx) with the embedded seal and the same letterhead.
 * Same option shape as exportReportPDF.
 */
export async function exportReportXLSX({
  title, subtitle, columns, rows, foot, user, filename, sheetName = 'Report',
}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = SYSTEM;
  wb.created = new Date();
  const ws = wb.addWorksheet(sheetName, {
    views: [{ showGridLines: false }],
  });

  const nCols = Math.max(columns.length, 4);
  const lastCol = String.fromCharCode(64 + nCols); // 'A' + (nCols-1)
  const { when, who } = stamp(user);

  // Letterhead: seal image floated top-left, text in merged rows to the right.
  const seal = await loadSeal();
  if (seal) {
    try {
      const imgId = wb.addImage({ base64: seal, extension: 'png' });
      ws.addImage(imgId, { tl: { col: 0.1, row: 0.1 }, ext: { width: 64, height: 64 } });
    } catch { /* ignore */ }
  }

  // Rows 1-4 hold the letterhead text (indented past the image via column B).
  const put = (row, text, opts = {}) => {
    ws.mergeCells(`B${row}:${lastCol}${row}`);
    const cell = ws.getCell(`B${row}`);
    cell.value = text;
    cell.font = opts.font || {};
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
    return cell;
  };
  put(1, ORG, { font: { bold: true, size: 13, color: { argb: 'FF156D07' } } });
  put(2, SYSTEM, { font: { size: 10, color: { argb: 'FF888888' } } });
  put(3, title, { font: { bold: true, size: 12, color: { argb: 'FF1E1E1E' } } });
  put(4, subtitle || '', { font: { size: 10, color: { argb: 'FF6E6E6E' } } });
  ws.getRow(1).height = 18;
  ws.getRow(2).height = 14;
  ws.getRow(3).height = 16;

  // Generation stamp row.
  ws.mergeCells(`A5:${lastCol}5`);
  const stampCell = ws.getCell('A5');
  stampCell.value = `Generated: ${when}          Generated by: ${who}`;
  stampCell.font = { size: 9, italic: true, color: { argb: 'FF888888' } };

  ws.addRow([]); // spacer (row 6)

  // Header row (row 7).
  const headerRow = ws.addRow(columns);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF156D07' } };
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
    cell.border = { bottom: { style: 'thin', color: { argb: 'FFCCCCCC' } } };
  });

  // Body.
  rows.forEach((r, i) => {
    const row = ws.addRow(r);
    if (i % 2 === 1) {
      row.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F5F5' } };
      });
    }
  });

  // Footer / totals.
  if (foot) {
    const f = ws.addRow(foot);
    f.eachCell((cell) => {
      cell.font = { bold: true, color: { argb: 'FF156D07' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDF4' } };
    });
  }

  // Auto-ish column widths from content.
  columns.forEach((h, i) => {
    let max = String(h).length;
    rows.forEach((r) => { max = Math.max(max, String(r[i] ?? '').length); });
    ws.getColumn(i + 1).width = Math.min(Math.max(max + 2, 10), 50);
  });

  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = stampedName(filename, 'xlsx');
  a.click();
  URL.revokeObjectURL(url);
}
